baseURL: "https://roaldnefs.com/"
languageCode: en-us
title: Roald Nefs
disqusShortname: roaldnefs

permalinks:
  posts: /posts/:year/:month/:slug/

menu:
  main:
    - name: Home
      url: "/"
      weight: 10