baseURL: "https://roaldnefs.com/"
languageCode: en-us
title: Roald Nefs
disqusShortname: roaldnefs
params:
  slogan: Roald Nefs, security specialist and open-source contributor

permalinks:
  posts: /posts/:year/:month/:slug/

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4

menu:
  main:
    - name: Articles
      url: "/posts/"
      weight: 10
    - name: About
      url: "/authors/roald-nefs/"
      weight: 20

taxonomies:
  author: authors
  tag: tags
  category: categories