baseURL: "https://roaldnefs.com/"
languageCode: en-us
title: Roald Nefs
disqusShortname: roaldnefs
params:
  slogan: Roald Nefs, SRE/DevOps engineer and open-source contributor

permalinks:
  posts: /posts/:year/:month/:slug/

menu:
  main:
    - name: Posts
      url: "/posts/"
      weight: 10