name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git for Github
        run: |
          git config --global user.name "Roald Nefs"
          git config --global user.email "roaldnefs@users.noreply.github.com"

      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          submodules: true

      - name: Set up Hugo
        env:
          HUGO_VERSION: 0.80.0
        run: |
          echo "installing hugo $HUGO_VERSION"
          curl -sL -o /tmp/hugo.deb \
          https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb && \
          sudo dpkg -i /tmp/hugo.deb && \
          rm /tmp/hugo.deb  

      - name: Publish
        env:
          REPOSITORY: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/roaldnefs/roaldnefs.com.git"
        run: ./publish.sh